FROM node:18-alpine as build-stage
WORKDIR /app

RUN corepack enable

COPY frontend/package*.json ./
RUN pnpm install

COPY frontend/ .
RUN pnpm run build

FROM nginx:alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
